---
title: "Teaching Lab Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  TeachingLab::TLDefault:
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(TeachingLab)
library(tidyverse)
library(gt)
library(here)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Quotes

```{r}
quotes1 <- read_csv(here("Data/SY20-21/SurveyMonkey/SY21-22 End-of-Session Participant Feedback Survey.csv")) %>%
  slice(-1) %>%
  drop_na(`What went well in today’s session?`) %>%
  select(`What went well in today’s session?`)

quotes2 <- read_csv(here("Data/SY20-21/SurveyMonkey/SY21-22 End-of-Session Participant Feedback Survey.csv")) %>%
  slice(-1) %>%
  drop_na(`What could have been better about today’s session?`) %>%
  select(`What could have been better about today’s session?`)
```

```{r}
quote_viz(quotes1, "What went well in today’s session?", viz_type = "gt", 
          highlight = c("participation", "time"), width = 40, 
          title = "Quotes in Response to: What went well in today’s session?") #%>%
  # gtsave(here::here("Images/2020-2021/SurveyMonkeyQuotes1.png"))
quote_viz(quotes2, "What could have been better about today’s session?", viz_type = "gt", 
          highlight = c("ignore"), width = 40, 
          title = "What could have been better about today’s session?") %>%
  gtsave(here::here("Images/2020-2021/SurveyMonkeyQuotes2.png"))
```


## Conclusions