---
title: "Teaching Lab 2019-2020 Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    css: styles.css
    self_contained: true # Other options are downcute, material, readthedown, html_clean, html_docco, lockdown, https://github.com/juba/rmdformats
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: kate # Also can do tango
    number_sections: false
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(readxl)
library(tidyverse)
library(here)
library(gt)

og_df <- read_excel(here("Data/SY19-20 Fall Spring merged.xlsx"))
second_df <- read_excel(here("Data/SY19-20 Fall-Spring Merged Dataset Update.xls"))
```

```{r echo = F}
htmltools::tagList(rmarkdown::html_dependency_font_awesome()) # Needed so fa's in footer will show
```

```{r cleaning, echo = F}
### Work from here
identifiers <- second_df %>%
  select(district, school, portfolio, id, merge)#, role, role2...10, role_txt)

fall_df <- second_df %>%
  select_at(vars(contains("pre"))) %>%
  bind_cols(identifiers) %>%
  relocate(merge, .after = last_col())


spring_df <- second_df %>%
  select_at(vars(contains("post"))) %>%
  bind_cols(identifiers) %>%
  relocate(merge, .after = last_col())


### ELA CONTENT: 12a-23d
## Average Scores
# 14a-14d, 18a-18d need recoding
fall_averages_ela <- fall_df %>%
  select(12:38) %>%
  summarise(
    pre12a = c(sum(pre12a == "Yes", na.rm = T)/sum(!is.na(pre12a)), length(which(!is.na(pre12a)))),
    pre12b = c(sum(pre12b == "Yes", na.rm = T)/sum(!is.na(pre12b)), length(which(!is.na(pre12b)))),
    pre12c = c(sum(pre12c == "No", na.rm = T)/sum(!is.na(pre12c)), length(which(!is.na(pre12c)))),
    pre12d = c(sum(pre12d == "No", na.rm = T)/sum(!is.na(pre12d)), length(which(!is.na(pre12d)))),
    pre13 = c(sum(pre13 == "A complex text that is worthy of reading multiple times.", na.rm = T)/sum(!is.na(pre13)), length(which(!is.na(pre13)))),
    pre14a = c(sum(pre14a == "True", na.rm = T)/sum(!is.na(pre14a)), length(which(!is.na(pre14a)))),
    pre14b = c(sum(pre14b == "True", na.rm = T)/sum(!is.na(pre14b)), length(which(!is.na(pre14b)))),
    pre14c = c(sum(pre14c == "False", na.rm = T)/sum(!is.na(pre14c)), length(which(!is.na(pre14c)))),
    pre14d = c(sum(pre14d == "False", na.rm = T)/sum(!is.na(pre14d)), length(which(!is.na(pre14d)))),
    pre15 = c(sum(pre15 == "Students independently read aloud texts at their reading level.", na.rm = T)/sum(!is.na(pre15)), length(which(!is.na(pre15)))),
    pre16 = c(sum(pre16 == "Ability to read complex text independently and proficiently.", na.rm = T)/sum(!is.na(pre16)), length(which(!is.na(pre16)))),
    pre17a = c(sum(pre17a == "Yes", na.rm = T)/sum(!is.na(pre17a)), length(which(!is.na(pre17a)))),
    pre17b = c(sum(pre17b == "Yes", na.rm = T)/sum(!is.na(pre17b)), length(which(!is.na(pre17b)))),
    pre17c = c(sum(pre17c == "No", na.rm = T)/sum(!is.na(pre17c)), length(which(!is.na(pre17c)))),
    pre17d = c(sum(pre17d == "No", na.rm = T)/sum(!is.na(pre17d)), length(which(!is.na(pre17d)))),
    pre18a = c(sum(pre18a == "True", na.rm = T)/sum(!is.na(pre18a)), length(which(!is.na(pre18a)))),
    pre18b = c(sum(pre18b == "True", na.rm = T)/sum(!is.na(pre18b)), length(which(!is.na(pre18b)))),
    pre18c = c(sum(pre18c == "False", na.rm = T)/sum(!is.na(pre18c)), length(which(!is.na(pre18c)))),
    pre18d = c(sum(pre18d == "False", na.rm = T)/sum(!is.na(pre18d)), length(which(!is.na(pre18d)))),
    pre19 = c(sum(pre19 == "Students pull out evidence from the text to explain their thinking in response to questions.", na.rm = T)/sum(!is.na(pre19)), length(which(!is.na(pre19)))),
    pre20 = c(sum(pre20 == "Students with low reading ability and a lot of knowledge about the food chain.", na.rm = T)/sum(!is.na(pre20)), length(which(!is.na(pre20)))),
    pre21 = c(sum(pre21 == "Have students read a series of additional texts at a variety of complexity levels on the topic.", na.rm = T)/sum(!is.na(pre21)), length(which(!is.na(pre21)))),
    pre22 = c(sum(pre22 == "Provide students with lower reading abilities an audio version of the main text to listen to before reading the main text in class.", na.rm = T)/sum(!is.na(pre22)), length(which(!is.na(pre22)))),
    pre23a = c(sum(pre23a == "Yes", na.rm = T)/sum(!is.na(pre23a)), length(which(!is.na(pre23a)))),
    pre23b = c(sum(pre23b == "Yes", na.rm = T)/sum(!is.na(pre23b)), length(which(!is.na(pre23b)))),
    pre23c = c(sum(pre23c == "No", na.rm = T)/sum(!is.na(pre23c)), length(which(!is.na(pre23c)))),
    pre23d = c(sum(pre23d == "No", na.rm = T)/sum(!is.na(pre23d)), length(which(!is.na(pre23d))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

fall_ela_n <- fall_averages_ela %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

### MATH CONTENT: 24a-32
fall_averages_math <- fall_df %>%
  select(38:59) %>%
  summarise(
    pre24a = c(sum(pre24a == "Yes", na.rm = T)/sum(!is.na(pre24a)), length(which(!is.na(pre24a)))),
    pre24b = c(sum(pre24b == "Yes", na.rm = T)/sum(!is.na(pre24b)), length(which(!is.na(pre24b)))),
    pre24c = c(sum(pre24c == "No", na.rm = T)/sum(!is.na(pre24c)), length(which(!is.na(pre24c)))),
    pre24d = c(sum(pre24d == "No", na.rm = T)/sum(!is.na(pre24d)), length(which(!is.na(pre24d)))),
    pre25 = c(sum(pre25 == "Giving students opportunities to develop deep commands of the how, why, and when of mathematical concepts.", na.rm = T)/sum(!is.na(pre25)), length(which(!is.na(pre25)))),
    pre26a = c(sum(pre26a == "Yes", na.rm = T)/sum(!is.na(pre26a)), length(which(!is.na(pre26a)))),
    pre26b = c(sum(pre26b == "Yes", na.rm = T)/sum(!is.na(pre26b)), length(which(!is.na(pre26b)))),
    pre26c = c(sum(pre26c == "No", na.rm = T)/sum(!is.na(pre26c)), length(which(!is.na(pre26c)))),
    pre26d = c(sum(pre26d == "No", na.rm = T)/sum(!is.na(pre26d)), length(which(!is.na(pre26d)))),
    pre27 = c(sum(pre27 == "Students’ beliefs about whether or not they are a “math person” influences their performance in math class.", na.rm = T)/sum(!is.na(pre27)), length(which(!is.na(pre27)))),
    pre28 = c(sum(pre28 == "Students need to receive on grade-level instruction every year in order to graduate high school ready for college and career.", na.rm = T)/sum(!is.na(pre28)), length(which(!is.na(pre28)))),
    pre29 = c(sum(pre29 == "Having the teacher simplify the language and task complexity for students who are English learners.", na.rm = T)/sum(!is.na(pre29)), length(which(!is.na(pre29)))),
    pre30a = c(sum(pre30a == "Yes", na.rm = T)/sum(!is.na(pre30a)), length(which(!is.na(pre30a)))),
    pre30b = c(sum(pre30b == "Yes", na.rm = T)/sum(!is.na(pre30b)), length(which(!is.na(pre30b)))),
    pre30c = c(sum(pre30c == "No", na.rm = T)/sum(!is.na(pre30c)), length(which(!is.na(pre30c)))),
    pre30d = c(sum(pre30d == "No", na.rm = T)/sum(!is.na(pre30d)), length(which(!is.na(pre30d)))),
    pre31a = c(sum(pre31a == "Yes", na.rm = T)/sum(!is.na(pre31a)), length(which(!is.na(pre31a)))),
    pre31b = c(sum(pre31b == "Yes", na.rm = T)/sum(!is.na(pre31b)), length(which(!is.na(pre31b)))),
    pre31c = c(sum(pre31c == "No", na.rm = T)/sum(!is.na(pre31c)), length(which(!is.na(pre31c)))),
    pre31d = c(sum(pre31d == "No", na.rm = T)/sum(!is.na(pre31d)), length(which(!is.na(pre31d)))),
    pre32 = c(sum(pre32 == "They describe how students will demonstrate their understanding.", na.rm = T)/sum(!is.na(pre32)), length(which(!is.na(pre32))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

fall_math_n <- fall_averages_math %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())


### ELA CONTENT: 12a-23d
## Average Scores
# 14a-14d, 18a-18d need recoding
spring_averages_ela <- spring_df %>%
  select(20:46) %>%
  summarise(
    post12a = c(sum(post12a == "Yes", na.rm = T)/sum(!is.na(post12a)), length(which(!is.na(post12a)))),
    post12b = c(sum(post12b == "Yes", na.rm = T)/sum(!is.na(post12b)), length(which(!is.na(post12b)))),
    post12c = c(sum(post12c == "No", na.rm = T)/sum(!is.na(post12c)), length(which(!is.na(post12c)))),
    post12d = c(sum(post12d == "No", na.rm = T)/sum(!is.na(post12d)), length(which(!is.na(post12d)))),
    post13 = c(sum(post13 == "A complex text that is worthy of reading multiple times.", na.rm = T)/sum(!is.na(post13)), length(which(!is.na(post13)))),
    post14a = c(sum(post14a == "True", na.rm = T)/sum(!is.na(post14a)), length(which(!is.na(post14a)))),
    post14b = c(sum(post14b == "True", na.rm = T)/sum(!is.na(post14b)), length(which(!is.na(post14b)))),
    post14c = c(sum(post14c == "False", na.rm = T)/sum(!is.na(post14c)), length(which(!is.na(post14c)))),
    post14d = c(sum(post14d == "False", na.rm = T)/sum(!is.na(post14d)), length(which(!is.na(post14d)))),
    post15 = c(sum(post15 == "Students independently read aloud texts at their reading level.", na.rm = T)/sum(!is.na(post15)), length(which(!is.na(post15)))),
    post16 = c(sum(post16 == "Ability to read complex text independently and proficiently.", na.rm = T)/sum(!is.na(post16)), length(which(!is.na(post16)))),
    post17a = c(sum(post17a == "Yes", na.rm = T)/sum(!is.na(post17a)), length(which(!is.na(post17a)))),
    post17b = c(sum(post17b == "Yes", na.rm = T)/sum(!is.na(post17b)), length(which(!is.na(post17b)))),
    post17c = c(sum(post17c == "No", na.rm = T)/sum(!is.na(post17c)), length(which(!is.na(post17c)))),
    post17d = c(sum(post17d == "No", na.rm = T)/sum(!is.na(post17d)), length(which(!is.na(post17d)))),
    post18a = c(sum(post18a == "True", na.rm = T)/sum(!is.na(post18a)), length(which(!is.na(post18a)))),
    post18b = c(sum(post18b == "True", na.rm = T)/sum(!is.na(post18b)), length(which(!is.na(post18b)))),
    post18c = c(sum(post18c == "False", na.rm = T)/sum(!is.na(post18c)), length(which(!is.na(post18c)))),
    post18d = c(sum(post18d == "False", na.rm = T)/sum(!is.na(post18d)), length(which(!is.na(post18d)))),
    post19 = c(sum(post19 == "Students pull out evidence from the text to explain their thinking in response to questions.", na.rm = T)/sum(!is.na(post19)), length(which(!is.na(post19)))),
    post20 = c(sum(post20 == "Students with low reading ability and a lot of knowledge about the food chain.", na.rm = T)/sum(!is.na(post20)), length(which(!is.na(post20)))),
    post21 = c(sum(post21 == "Have students read a series of additional texts at a variety of complexity levels on the topic.", na.rm = T)/sum(!is.na(post21)), length(which(!is.na(post21)))),
    post22 = c(sum(post22 == "Provide students with lower reading abilities an audio version of the main text to listen to before reading the main text in class.", na.rm = T)/sum(!is.na(post22)), length(which(!is.na(post22)))),
    post23a = c(sum(post23a == "Yes", na.rm = T)/sum(!is.na(post23a)), length(which(!is.na(post23a)))),
    post23b = c(sum(post23b == "Yes", na.rm = T)/sum(!is.na(post23b)), length(which(!is.na(post23b)))),
    post23c = c(sum(post23c == "No", na.rm = T)/sum(!is.na(post23c)), length(which(!is.na(post23c)))),
    post23d = c(sum(post23d == "No", na.rm = T)/sum(!is.na(post23d)), length(which(!is.na(post23d))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

spring_ela_n <- spring_averages_ela %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

## Constructs within


### MATH CONTENT: 24a-32
spring_averages_math <- spring_df %>%
  select(47:67) %>%
  summarise(
    post24a = c(sum(post24a == "Yes", na.rm = T)/sum(!is.na(post24a)), length(which(!is.na(post24a)))),
    post24b = c(sum(post24b == "Yes", na.rm = T)/sum(!is.na(post24b)), length(which(!is.na(post24b)))),
    post24c = c(sum(post24c == "No", na.rm = T)/sum(!is.na(post24c)), length(which(!is.na(post24c)))),
    post24d = c(sum(post24d == "No", na.rm = T)/sum(!is.na(post24d)), length(which(!is.na(post24d)))),
    post25 = c(sum(post25 == "Giving students opportunities to develop deep commands of the how, why, and when of mathematical concepts.", na.rm = T)/sum(!is.na(post25)), length(which(!is.na(post25)))),
    post26a = c(sum(post26a == "Yes", na.rm = T)/sum(!is.na(post26a)), length(which(!is.na(post26a)))),
    post26b = c(sum(post26b == "Yes", na.rm = T)/sum(!is.na(post26b)), length(which(!is.na(post26b)))),
    post26c = c(sum(post26c == "No", na.rm = T)/sum(!is.na(post26c)), length(which(!is.na(post26c)))),
    post26d = c(sum(post26d == "No", na.rm = T)/sum(!is.na(post26d)), length(which(!is.na(post26d)))),
    post27 = c(sum(post27 == "Students’ beliefs about whether or not they are a “math person” influences their performance in math class.", na.rm = T)/sum(!is.na(post27)), length(which(!is.na(post27)))),
    post28 = c(sum(post28 == "Students need to receive on grade-level instruction every year in order to graduate high school ready for college and career.", na.rm = T)/sum(!is.na(post28)), length(which(!is.na(post28)))),
    post29 = c(sum(post29 == "Having the teacher simplify the language and task complexity for students who are English learners.", na.rm = T)/sum(!is.na(post29)), length(which(!is.na(post29)))),
    post30a = c(sum(post30a == "Yes", na.rm = T)/sum(!is.na(post30a)), length(which(!is.na(post30a)))),
    post30b = c(sum(post30b == "Yes", na.rm = T)/sum(!is.na(post30b)), length(which(!is.na(post30b)))),
    post30c = c(sum(post30c == "No", na.rm = T)/sum(!is.na(post30c)), length(which(!is.na(post30c)))),
    post30d = c(sum(post30d == "No", na.rm = T)/sum(!is.na(post30d)), length(which(!is.na(post30d)))),
    post31a = c(sum(post31a == "Yes", na.rm = T)/sum(!is.na(post31a)), length(which(!is.na(post31a)))),
    post31b = c(sum(post31b == "Yes", na.rm = T)/sum(!is.na(post31b)), length(which(!is.na(post31b)))),
    post31c = c(sum(post31c == "No", na.rm = T)/sum(!is.na(post31c)), length(which(!is.na(post31c)))),
    post31d = c(sum(post31d == "No", na.rm = T)/sum(!is.na(post31d)), length(which(!is.na(post31d)))),
    post32 = c(sum(post32 == "They describe how students will demonstrate their understanding.", na.rm = T)/sum(!is.na(post32)), length(which(!is.na(post32))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

spring_math_n <- spring_averages_math %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

### JOINING FALL AND SPRING
## EL
fall_spring_el_averages <- bind_rows(fall_averages_ela %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre")),
                                     spring_averages_ela %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")),
                                     spring_averages_ela %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")) - 
                                       fall_averages_ela %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre"))) %>%
  rownames_to_column() %>%
  pivot_longer(-rowname, 'variable', 'value') %>%
  pivot_wider(variable, rowname) %>%
  rename(Question = variable, Fall = `1`, Spring = `2`, Improvement = `3`) %>%
  bind_cols(n2 = spring_ela_n$value, n1 = fall_ela_n$value) %>%
  relocate(n2, .after = `Spring`) %>%
  relocate(n1, .after = `Fall`)
## MATH
fall_spring_math_averages <- bind_rows(fall_averages_math %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre")), 
                                       spring_averages_math %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")),
                                       spring_averages_math %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")) - 
                                         fall_averages_math %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre"))) %>%
  rownames_to_column() %>%
  pivot_longer(-rowname, 'variable', 'value') %>%
  pivot_wider(variable, rowname) %>%
  rename(Question = variable, Fall = `1`, Spring = `2`, Improvement = `3`) %>%
  bind_cols(n2 = spring_math_n$value, n1 = fall_math_n$value) %>%
  relocate(n2, .after = `Spring`) %>%
  relocate(n1, .after = `Fall`)
```

```{r math-question-key}
question_key2 <- tibble(Number = c('24a', '24b', '24c', '24d', '25', '26a', '26b', '26c', '26d', '27', '28', '29', '30a', '30b', '30c', '30d', '31a', '31b', '31c', '31d', '32'),
                       Question = c(rep("Which of the following statements describe math instructional shifts, and which do not?", 4),
                                    "What does “rigor” mean in math instruction, as defined by the instructional shifts?",
                                    rep("Which of the following statements describe student mindsets and habits that must be in place in order to execute a problem-based approach effectively?", 4),
                                    "Which of the following statements is true about math identities?",
                                    "What is the MOST important reason for ensuring that all students receive on grade-level instruction in math?",
                                    "Which of the following is an INEFFECTIVE strategy for equitably involving students who are English learners in classroom discussions?",
                                    rep("A teacher can take several different approaches to identify unfinished learning for students. Which of the following are actions they should take?", 4),
                                    rep("Which of the following actions describe equitable instructional strategies for supporting students with unfinished learning in math", 4),
                                    "Which of the following BEST describes one purpose of mathematics learning goals?"))
```


```{r ela-question-key}
question_key <- tibble(Number = c('12a', '12b', '12c', '12d', '13', '14a', '14b', '14c', '14d', '15', '16', '17a', '17b', '17c', '17d', '18a', '18b', '18c', '18d', '19', '20', '21', '22', '23a', '23b', '23c', '23d'),
       Question = c(rep("Which of the following are literacy instructional shifts, and which are not?", 4),
                    "When designing literacy lessons, teachers should start with which of the following?",
                    rep("Which of the following statements are true about the relationship between reading fluency and reading comprehension, and which are false?", 4),
                    "Which of the following is NOT an effective strategy for improving student fluency?",
                    "Which of the following is the single biggest differentiator of college and career-readiness?",
                    rep("Which of the following approaches for selecting texts for whole-class reading instruction are aligned with post-shifts literacy instruction and which are not", 4),
                    rep("Which of the following statements are true about reading the same complex text multiple times?", 4),
                    "Which of the following describes something students might do during close reading of complex texts?",
                    "Mrs. Richards’ students have a range of reading proficiency and knowledge about the food chain. When reading a grade-level complex text about this topic, which group of students is most likely to perform better on comprehension questions?",
                    "How could Mrs. Richards best prepare students to build knowledge about the topic of the food chain?",
                    "The main text that the students in Ms. Blackwell’s class is about to read is likely to be very difficult for the majority of the class. Which of the following is a strategy that Ms. Blackwell could use with her students with lower reading abilities?",
                    rep("Which of the following describe strategies for supporting struggling readers, and which do not?", 4)))
```

# Breakdown by Content Knowledge

## ELA Table

```{r}
el_table_grouped <- fall_spring_el_averages %>%
   mutate(Content = c(rep("ELA General Standards and Shifts", 5),
                      rep("Fluency", 5),
                      rep("Text Complexity", 5),
                      rep("Evidence & Close Reading", 5),
                      rep("Building Knowledge", 2),
                      rep("Supporting Students with Unfinished Learning", 5))) %>%
  gt::gt(groupname_col = "Content") %>%
  tab_header(
    title = md("**ELA Scores in Fall vs. Spring**")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
  gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  summary_rows(groups = T,
               columns = vars(n1, n2),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_number
               ) %>%
  summary_rows(groups = T,
               columns = vars(Fall, Spring, Improvement),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_percent,
               scale_values = F
               ) %>%
  tab_style(style = list(
      cell_text(style = "italic",
              weight = "bold"),
      cell_fill(color = "#377A98")
    ),
    locations = cells_summary(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", 
                  "Evidence & Close Reading", "Building Knowledge", "Supporting Students with Unfinished Learning"),
      columns = vars(Improvement)
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_row_groups(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", 
                  "Evidence & Close Reading", "Building Knowledge", "Supporting Students with Unfinished Learning")
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(style = "italic")
    ),
    locations = cells_summary(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", "Evidence & Close Reading",
                 "Building Knowledge", "Supporting Students with Unfinished Learning"),
      columns = everything()
    )
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold"),
      cell_fill(color = "#00743F")
    ),
    locations = cells_grand_summary(
      columns = everything()
    )
  )

el_table_grouped %>%
  gtsave(filename = "GroupedSY19-20ELScores.png", path = here("Images/"))
```

::: aside

**ELA Question Key**

```{r}
key1 <- question_key %>%
  gt() %>%
  cols_width(
    2 ~ px(200),
    1 ~ px(69)
  ) %>%
  cols_label(
    Question = md("**Question**"),
    Number = md("**Number**")
  ) %>%
  cols_align(
    align = "center"
  )

key1 %>%
  gtsave(here("Images/el_key.png"))
```

:::

## Math Table

```{r}
math_table_grouped <- fall_spring_math_averages %>%
   mutate(Content = c(rep("General Standards & Shifts", 5),
                      rep("Math Mindsets & Identities", 5),
                      rep("Principles of Math Equitable Instruction", 2),
                      rep("Supporting Students with Unfinished Learning", 8),
                      "Math Learning Goal")) %>%
  gt::gt(groupname_col = "Content") %>%
  tab_header(
    title = md("**Math Scores in Fall vs. Spring**")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
   gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  summary_rows(groups = T,
               columns = vars(n1, n2),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_number
               ) %>%
  summary_rows(groups = T,
               columns = vars(Fall, Spring, Improvement),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_percent,
               scale_values = F
               ) %>%
  tab_style(style = list(
      cell_text(style = "italic",
              weight = "bold"),
      cell_fill(color = "#377A98")
    ),
    locations = cells_summary(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal"),
      columns = vars(Improvement)
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_row_groups(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal")
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(style = "italic")
    ),
    locations = cells_summary(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal"),
      columns = everything()
    )
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold"),
      cell_fill(color = "#00743F")
    ),
    locations = cells_grand_summary(
      columns = everything()
    )
  )

math_table_grouped %>%
  gtsave(filename = "GroupedSY19-20MathScores.png", path = here("Images/"))
```

::: aside

**Math Question Key**

```{r}
key2 <- question_key2 %>%
  gt() %>%
  cols_label(
    Question = md("**Question**"),
    Number = md("**Number**")
  ) %>%
  cols_align(
    align = "center"
  )

key2 %>%
  gtsave(here("Images/math_key.png"))
```

:::

# Matched Analysis

```{r}
fall_averages_ela_matched <- fall_df %>%
  dplyr::filter(merge == 3) %>%
  select(12:38) %>%
  filter(rowSums(across(everything(), ~ is.na(.))) < 3) %>%
  summarise(
    pre12a = c(sum(pre12a == "Yes", na.rm = T)/sum(!is.na(pre12a)), length(which(!is.na(pre12a)))),
    pre12b = c(sum(pre12b == "Yes", na.rm = T)/sum(!is.na(pre12b)), length(which(!is.na(pre12b)))),
    pre12c = c(sum(pre12c == "No", na.rm = T)/sum(!is.na(pre12c)), length(which(!is.na(pre12c)))),
    pre12d = c(sum(pre12d == "No", na.rm = T)/sum(!is.na(pre12d)), length(which(!is.na(pre12d)))),
    pre13 = c(sum(pre13 == "A complex text that is worthy of reading multiple times.", na.rm = T)/sum(!is.na(pre13)), length(which(!is.na(pre13)))),
    pre14a = c(sum(pre14a == "True", na.rm = T)/sum(!is.na(pre14a)), length(which(!is.na(pre14a)))),
    pre14b = c(sum(pre14b == "True", na.rm = T)/sum(!is.na(pre14b)), length(which(!is.na(pre14b)))),
    pre14c = c(sum(pre14c == "False", na.rm = T)/sum(!is.na(pre14c)), length(which(!is.na(pre14c)))),
    pre14d = c(sum(pre14d == "False", na.rm = T)/sum(!is.na(pre14d)), length(which(!is.na(pre14d)))),
    pre15 = c(sum(pre15 == "Students independently read aloud texts at their reading level.", na.rm = T)/sum(!is.na(pre15)), length(which(!is.na(pre15)))),
    pre16 = c(sum(pre16 == "Ability to read complex text independently and proficiently.", na.rm = T)/sum(!is.na(pre16)), length(which(!is.na(pre16)))),
    pre17a = c(sum(pre17a == "Yes", na.rm = T)/sum(!is.na(pre17a)), length(which(!is.na(pre17a)))),
    pre17b = c(sum(pre17b == "Yes", na.rm = T)/sum(!is.na(pre17b)), length(which(!is.na(pre17b)))),
    pre17c = c(sum(pre17c == "No", na.rm = T)/sum(!is.na(pre17c)), length(which(!is.na(pre17c)))),
    pre17d = c(sum(pre17d == "No", na.rm = T)/sum(!is.na(pre17d)), length(which(!is.na(pre17d)))),
    pre18a = c(sum(pre18a == "True", na.rm = T)/sum(!is.na(pre18a)), length(which(!is.na(pre18a)))),
    pre18b = c(sum(pre18b == "True", na.rm = T)/sum(!is.na(pre18b)), length(which(!is.na(pre18b)))),
    pre18c = c(sum(pre18c == "False", na.rm = T)/sum(!is.na(pre18c)), length(which(!is.na(pre18c)))),
    pre18d = c(sum(pre18d == "False", na.rm = T)/sum(!is.na(pre18d)), length(which(!is.na(pre18d)))),
    pre19 = c(sum(pre19 == "Students pull out evidence from the text to explain their thinking in response to questions.", na.rm = T)/sum(!is.na(pre19)), length(which(!is.na(pre19)))),
    pre20 = c(sum(pre20 == "Students with low reading ability and a lot of knowledge about the food chain.", na.rm = T)/sum(!is.na(pre20)), length(which(!is.na(pre20)))),
    pre21 = c(sum(pre21 == "Have students read a series of additional texts at a variety of complexity levels on the topic.", na.rm = T)/sum(!is.na(pre21)), length(which(!is.na(pre21)))),
    pre22 = c(sum(pre22 == "Provide students with lower reading abilities an audio version of the main text to listen to before reading the main text in class.", na.rm = T)/sum(!is.na(pre22)), length(which(!is.na(pre22)))),
    pre23a = c(sum(pre23a == "Yes", na.rm = T)/sum(!is.na(pre23a)), length(which(!is.na(pre23a)))),
    pre23b = c(sum(pre23b == "Yes", na.rm = T)/sum(!is.na(pre23b)), length(which(!is.na(pre23b)))),
    pre23c = c(sum(pre23c == "No", na.rm = T)/sum(!is.na(pre23c)), length(which(!is.na(pre23c)))),
    pre23d = c(sum(pre23d == "No", na.rm = T)/sum(!is.na(pre23d)), length(which(!is.na(pre23d))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

fall_ela_n_matched <- fall_averages_ela_matched %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

### MATH CONTENT: 24a-32
fall_averages_math_matched <- fall_df %>%
  dplyr::filter(merge == 3) %>%
  select(38:59) %>%
  filter(rowSums(across(everything(), ~ is.na(.))) < 3) %>%
  summarise(
    pre24a = c(sum(pre24a == "Yes", na.rm = T)/sum(!is.na(pre24a)), length(which(!is.na(pre24a)))),
    pre24b = c(sum(pre24b == "Yes", na.rm = T)/sum(!is.na(pre24b)), length(which(!is.na(pre24b)))),
    pre24c = c(sum(pre24c == "No", na.rm = T)/sum(!is.na(pre24c)), length(which(!is.na(pre24c)))),
    pre24d = c(sum(pre24d == "No", na.rm = T)/sum(!is.na(pre24d)), length(which(!is.na(pre24d)))),
    pre25 = c(sum(pre25 == "Giving students opportunities to develop deep commands of the how, why, and when of mathematical concepts.", na.rm = T)/sum(!is.na(pre25)), length(which(!is.na(pre25)))),
    pre26a = c(sum(pre26a == "Yes", na.rm = T)/sum(!is.na(pre26a)), length(which(!is.na(pre26a)))),
    pre26b = c(sum(pre26b == "Yes", na.rm = T)/sum(!is.na(pre26b)), length(which(!is.na(pre26b)))),
    pre26c = c(sum(pre26c == "No", na.rm = T)/sum(!is.na(pre26c)), length(which(!is.na(pre26c)))),
    pre26d = c(sum(pre26d == "No", na.rm = T)/sum(!is.na(pre26d)), length(which(!is.na(pre26d)))),
    pre27 = c(sum(pre27 == "Students’ beliefs about whether or not they are a “math person” influences their performance in math class.", na.rm = T)/sum(!is.na(pre27)), length(which(!is.na(pre27)))),
    pre28 = c(sum(pre28 == "Students need to receive on grade-level instruction every year in order to graduate high school ready for college and career.", na.rm = T)/sum(!is.na(pre28)), length(which(!is.na(pre28)))),
    pre29 = c(sum(pre29 == "Having the teacher simplify the language and task complexity for students who are English learners.", na.rm = T)/sum(!is.na(pre29)), length(which(!is.na(pre29)))),
    pre30a = c(sum(pre30a == "Yes", na.rm = T)/sum(!is.na(pre30a)), length(which(!is.na(pre30a)))),
    pre30b = c(sum(pre30b == "Yes", na.rm = T)/sum(!is.na(pre30b)), length(which(!is.na(pre30b)))),
    pre30c = c(sum(pre30c == "No", na.rm = T)/sum(!is.na(pre30c)), length(which(!is.na(pre30c)))),
    pre30d = c(sum(pre30d == "No", na.rm = T)/sum(!is.na(pre30d)), length(which(!is.na(pre30d)))),
    pre31a = c(sum(pre31a == "Yes", na.rm = T)/sum(!is.na(pre31a)), length(which(!is.na(pre31a)))),
    pre31b = c(sum(pre31b == "Yes", na.rm = T)/sum(!is.na(pre31b)), length(which(!is.na(pre31b)))),
    pre31c = c(sum(pre31c == "No", na.rm = T)/sum(!is.na(pre31c)), length(which(!is.na(pre31c)))),
    pre31d = c(sum(pre31d == "No", na.rm = T)/sum(!is.na(pre31d)), length(which(!is.na(pre31d)))),
    pre32 = c(sum(pre32 == "They describe how students will demonstrate their understanding.", na.rm = T)/sum(!is.na(pre32)), length(which(!is.na(pre32))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

fall_math_n_matched <- fall_averages_math_matched %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())


### ELA CONTENT: 12a-23d
## Average Scores
# 14a-14d, 18a-18d need recoding
spring_averages_ela_matched <- spring_df %>%
  dplyr::filter(merge == 3) %>%
  select(20:46) %>%
  filter(rowSums(across(everything(), ~ is.na(.))) < 3) %>%
  summarise(
    post12a = c(sum(post12a == "Yes", na.rm = T)/sum(!is.na(post12a)), length(which(!is.na(post12a)))),
    post12b = c(sum(post12b == "Yes", na.rm = T)/sum(!is.na(post12b)), length(which(!is.na(post12b)))),
    post12c = c(sum(post12c == "No", na.rm = T)/sum(!is.na(post12c)), length(which(!is.na(post12c)))),
    post12d = c(sum(post12d == "No", na.rm = T)/sum(!is.na(post12d)), length(which(!is.na(post12d)))),
    post13 = c(sum(post13 == "A complex text that is worthy of reading multiple times.", na.rm = T)/sum(!is.na(post13)), length(which(!is.na(post13)))),
    post14a = c(sum(post14a == "True", na.rm = T)/sum(!is.na(post14a)), length(which(!is.na(post14a)))),
    post14b = c(sum(post14b == "True", na.rm = T)/sum(!is.na(post14b)), length(which(!is.na(post14b)))),
    post14c = c(sum(post14c == "False", na.rm = T)/sum(!is.na(post14c)), length(which(!is.na(post14c)))),
    post14d = c(sum(post14d == "False", na.rm = T)/sum(!is.na(post14d)), length(which(!is.na(post14d)))),
    post15 = c(sum(post15 == "Students independently read aloud texts at their reading level.", na.rm = T)/sum(!is.na(post15)), length(which(!is.na(post15)))),
    post16 = c(sum(post16 == "Ability to read complex text independently and proficiently.", na.rm = T)/sum(!is.na(post16)), length(which(!is.na(post16)))),
    post17a = c(sum(post17a == "Yes", na.rm = T)/sum(!is.na(post17a)), length(which(!is.na(post17a)))),
    post17b = c(sum(post17b == "Yes", na.rm = T)/sum(!is.na(post17b)), length(which(!is.na(post17b)))),
    post17c = c(sum(post17c == "No", na.rm = T)/sum(!is.na(post17c)), length(which(!is.na(post17c)))),
    post17d = c(sum(post17d == "No", na.rm = T)/sum(!is.na(post17d)), length(which(!is.na(post17d)))),
    post18a = c(sum(post18a == "True", na.rm = T)/sum(!is.na(post18a)), length(which(!is.na(post18a)))),
    post18b = c(sum(post18b == "True", na.rm = T)/sum(!is.na(post18b)), length(which(!is.na(post18b)))),
    post18c = c(sum(post18c == "False", na.rm = T)/sum(!is.na(post18c)), length(which(!is.na(post18c)))),
    post18d = c(sum(post18d == "False", na.rm = T)/sum(!is.na(post18d)), length(which(!is.na(post18d)))),
    post19 = c(sum(post19 == "Students pull out evidence from the text to explain their thinking in response to questions.", na.rm = T)/sum(!is.na(post19)), length(which(!is.na(post19)))),
    post20 = c(sum(post20 == "Students with low reading ability and a lot of knowledge about the food chain.", na.rm = T)/sum(!is.na(post20)), length(which(!is.na(post20)))),
    post21 = c(sum(post21 == "Have students read a series of additional texts at a variety of complexity levels on the topic.", na.rm = T)/sum(!is.na(post21)), length(which(!is.na(post21)))),
    post22 = c(sum(post22 == "Provide students with lower reading abilities an audio version of the main text to listen to before reading the main text in class.", na.rm = T)/sum(!is.na(post22)), length(which(!is.na(post22)))),
    post23a = c(sum(post23a == "Yes", na.rm = T)/sum(!is.na(post23a)), length(which(!is.na(post23a)))),
    post23b = c(sum(post23b == "Yes", na.rm = T)/sum(!is.na(post23b)), length(which(!is.na(post23b)))),
    post23c = c(sum(post23c == "No", na.rm = T)/sum(!is.na(post23c)), length(which(!is.na(post23c)))),
    post23d = c(sum(post23d == "No", na.rm = T)/sum(!is.na(post23d)), length(which(!is.na(post23d))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

spring_ela_n_matched <- spring_averages_ela_matched %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

## Constructs within


### MATH CONTENT: 24a-32
spring_averages_math_matched <- spring_df %>%
  dplyr::filter(merge == 3) %>%
  select(47:67) %>%
  filter(rowSums(across(everything(), ~ is.na(.))) < 3) %>%
  summarise(
    post24a = c(sum(post24a == "Yes", na.rm = T)/sum(!is.na(post24a)), length(which(!is.na(post24a)))),
    post24b = c(sum(post24b == "Yes", na.rm = T)/sum(!is.na(post24b)), length(which(!is.na(post24b)))),
    post24c = c(sum(post24c == "No", na.rm = T)/sum(!is.na(post24c)), length(which(!is.na(post24c)))),
    post24d = c(sum(post24d == "No", na.rm = T)/sum(!is.na(post24d)), length(which(!is.na(post24d)))),
    post25 = c(sum(post25 == "Giving students opportunities to develop deep commands of the how, why, and when of mathematical concepts.", na.rm = T)/sum(!is.na(post25)), length(which(!is.na(post25)))),
    post26a = c(sum(post26a == "Yes", na.rm = T)/sum(!is.na(post26a)), length(which(!is.na(post26a)))),
    post26b = c(sum(post26b == "Yes", na.rm = T)/sum(!is.na(post26b)), length(which(!is.na(post26b)))),
    post26c = c(sum(post26c == "No", na.rm = T)/sum(!is.na(post26c)), length(which(!is.na(post26c)))),
    post26d = c(sum(post26d == "No", na.rm = T)/sum(!is.na(post26d)), length(which(!is.na(post26d)))),
    post27 = c(sum(post27 == "Students’ beliefs about whether or not they are a “math person” influences their performance in math class.", na.rm = T)/sum(!is.na(post27)), length(which(!is.na(post27)))),
    post28 = c(sum(post28 == "Students need to receive on grade-level instruction every year in order to graduate high school ready for college and career.", na.rm = T)/sum(!is.na(post28)), length(which(!is.na(post28)))),
    post29 = c(sum(post29 == "Having the teacher simplify the language and task complexity for students who are English learners.", na.rm = T)/sum(!is.na(post29)), length(which(!is.na(post29)))),
    post30a = c(sum(post30a == "Yes", na.rm = T)/sum(!is.na(post30a)), length(which(!is.na(post30a)))),
    post30b = c(sum(post30b == "Yes", na.rm = T)/sum(!is.na(post30b)), length(which(!is.na(post30b)))),
    post30c = c(sum(post30c == "No", na.rm = T)/sum(!is.na(post30c)), length(which(!is.na(post30c)))),
    post30d = c(sum(post30d == "No", na.rm = T)/sum(!is.na(post30d)), length(which(!is.na(post30d)))),
    post31a = c(sum(post31a == "Yes", na.rm = T)/sum(!is.na(post31a)), length(which(!is.na(post31a)))),
    post31b = c(sum(post31b == "Yes", na.rm = T)/sum(!is.na(post31b)), length(which(!is.na(post31b)))),
    post31c = c(sum(post31c == "No", na.rm = T)/sum(!is.na(post31c)), length(which(!is.na(post31c)))),
    post31d = c(sum(post31d == "No", na.rm = T)/sum(!is.na(post31d)), length(which(!is.na(post31d)))),
    post32 = c(sum(post32 == "They describe how students will demonstrate their understanding.", na.rm = T)/sum(!is.na(post32)), length(which(!is.na(post32))))
  ) %>%
  dplyr::mutate(across(everything(), ~ .x * 100))

spring_math_n_matched <- spring_averages_math_matched %>% slice(2) %>%
  dplyr::mutate(across(everything(), ~ .x / 100)) %>%
  pivot_longer(everything())

### JOINING FALL AND SPRING
## EL
fall_spring_el_averages_matched <- bind_rows(fall_averages_ela_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre")),
                                     spring_averages_ela_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")),
                                     spring_averages_ela_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")) - 
                                       fall_averages_ela_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre"))) %>%
  rownames_to_column() %>%
  pivot_longer(-rowname, 'variable', 'value') %>%
  pivot_wider(variable, rowname) %>%
  rename(Question = variable, Fall = `1`, Spring = `2`, Improvement = `3`) %>%
  bind_cols(n2 = spring_ela_n_matched$value, n1 = fall_ela_n_matched$value) %>%
  relocate(n2, .after = `Spring`) %>%
  relocate(n1, .after = `Fall`)
## MATH
fall_spring_math_averages_matched <- bind_rows(fall_averages_math_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre")), 
                                       spring_averages_math_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")),
                                       spring_averages_math_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "post")) - 
                                         fall_averages_math_matched %>% slice(-2) %>% rename_with( ~ str_remove_all(.x, "pre"))) %>%
  rownames_to_column() %>%
  pivot_longer(-rowname, 'variable', 'value') %>%
  pivot_wider(variable, rowname) %>%
  rename(Question = variable, Fall = `1`, Spring = `2`, Improvement = `3`) %>%
  bind_cols(n2 = spring_math_n_matched$value, n1 = fall_math_n_matched$value) %>%
  relocate(n2, .after = `Spring`) %>%
  relocate(n1, .after = `Fall`)
```

## Math Table Matched and Grouped

```{r}
math_table_grouped_matched <- fall_spring_math_averages_matched %>%
   mutate(Content = c(rep("General Standards & Shifts", 5),
                      rep("Math Mindsets & Identities", 5),
                      rep("Principles of Math Equitable Instruction", 2),
                      rep("Supporting Students with Unfinished Learning", 8),
                      "Math Learning Goal")) %>%
  gt::gt(groupname_col = "Content") %>%
  tab_header(
    title = md("**Math Matched Scores in Fall vs. Spring**"),
    subtitle = md("*Those with at least a 75% response rate*")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
   gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  summary_rows(groups = T,
               columns = vars(n1, n2),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_number
               ) %>%
  summary_rows(groups = T,
               columns = vars(Fall, Spring, Improvement),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_percent,
               scale_values = F
               ) %>%
  tab_style(style = list(
      cell_text(style = "italic",
              weight = "bold"),
      cell_fill(color = "#377A98")
    ),
    locations = cells_summary(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal"),
      columns = vars(Improvement)
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_row_groups(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal")
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(style = "italic")
    ),
    locations = cells_summary(
      groups = c("General Standards & Shifts", "Math Mindsets & Identities", 
"Principles of Math Equitable Instruction", "Supporting Students with Unfinished Learning", 
"Math Learning Goal"),
      columns = everything()
    )
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold"),
      cell_fill(color = "#00743F")
    ),
    locations = cells_grand_summary(
      columns = everything()
    )
  )

math_table_grouped_matched %>%
  gtsave(filename = "GroupedSY19-20MathScores_Matched.png", path = here("Images/"))
```

## ELA Table Matched and Grouped

```{r}
el_table_grouped_matched <- fall_spring_el_averages_matched %>%
   mutate(Content = c(rep("ELA General Standards and Shifts", 5),
                      rep("Fluency", 5),
                      rep("Text Complexity", 5),
                      rep("Evidence & Close Reading", 5),
                      rep("Building Knowledge", 2),
                      rep("Supporting Students with Unfinished Learning", 5))) %>%
  gt::gt(groupname_col = "Content") %>%
  tab_header(
    title = md("**ELA Matched Scores in Fall vs. Spring**"),
    subtitle = md("*Those with at least a 75% response rate*")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
  gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  summary_rows(groups = T,
               columns = vars(n1, n2),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_number
               ) %>%
  summary_rows(groups = T,
               columns = vars(Fall, Spring, Improvement),
               fns = list(
                 `Block Average` = ~ mean(.)),
               formatter = fmt_percent,
               scale_values = F
               ) %>%
  tab_style(style = list(
      cell_text(style = "italic",
              weight = "bold"),
      cell_fill(color = "#377A98")
    ),
    locations = cells_summary(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", 
                  "Evidence & Close Reading", "Building Knowledge", "Supporting Students with Unfinished Learning"),
      columns = vars(Improvement)
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_row_groups(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", 
                  "Evidence & Close Reading", "Building Knowledge", "Supporting Students with Unfinished Learning")
    )
  ) %>%
  tab_style(
    style = list(
      cell_text(style = "italic")
    ),
    locations = cells_summary(
      groups = c("ELA General Standards and Shifts", "Fluency", "Text Complexity", "Evidence & Close Reading",
                 "Building Knowledge", "Supporting Students with Unfinished Learning"),
      columns = everything()
    )
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold"),
      cell_fill(color = "#00743F")
    ),
    locations = cells_grand_summary(
      columns = everything()
    )
  )

el_table_grouped_matched %>%
  gtsave(filename = "GroupedSY19-20ELScores_Matched.png", path = here("Images/"))
```


# Overall Improvement for Each Question

## ELA

Here's what ELA looks like by question:

```{r}
### Making Summary Tables
## EL
el_table <- fall_spring_el_averages %>%
  gt::gt() %>%
  tab_header(
    title = md("**ELA Scores in Fall vs. Spring**")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
  # tab_style(
  #   style = cell_fill(color = "forestgreen", alpha = 0.2),
  #   locations = cells_body(
  #     columns = vars(Improvement),
  #     rows = Improvement > 0
  #     )
  # ) %>%
  gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  )
el_table %>%
  gtsave(here("Images/SY19-20ELScores.png"))
```

## Math

Here's what math improvement over time looks like by question

```{r pressure, echo=FALSE}
math_table <- fall_spring_math_averages %>%
  gt::gt() %>%
  tab_header(
    title = md("**Math Scores in Fall vs. Spring**")
  ) %>%
   cols_label(
     n1 = gt::html("n<sub>1</sub>"),
     n2 = gt::html("n<sub>2</sub>")
   ) %>%
    # tab_style(
    #   style = cell_fill(color = "forestgreen", alpha = 0.2),
    #   locations = cells_body(
    #     columns = vars(Improvement),
    #     rows = Improvement > 0
    #   )
    # ) %>%
   gt::data_color(
     columns = gt::vars(Improvement),
     colors = scales::col_numeric(
       palette = ggsci::rgb_material('light-green'),
       domain = NULL
     )
   ) %>%
  fmt_percent(
    columns = vars(Fall, Spring, Improvement),
    decimals = 2,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(Fall, Spring, Improvement),
    fns = list(
      Average = ~ mean(.)
    ),
    formatter = fmt_percent,
    scale_values = F
  ) %>%
  grand_summary_rows(
    columns = vars(n1, n2),
    fns = list(
      Average = ~ round(mean(.))
    ),
    formatter = fmt_number
  )
math_table %>%
  gtsave(filename = "SY19-20MathScores.png", path = here("Images/"))
```


```{r savetopdf}
pagedown::chrome_print(input = here("R/2019-2020Report.html"),
                       output = here("PDF/2019-2020Report.pdf"))
```

